- name: "***** BACKEND GOPHISH: Set up client profiles *****"
  include_tasks: backend-ovpn-clients.yml

- name: "***** BACKEND GOPHISH: Set up GoPhish *****"
  include_tasks: gophish-setup.yml

- name: "***** BACKEND GOPHISH: Write Help information *****"
  include_tasks: write-help.yml
