#!/bin/bash

orange=$(printf '\033[0;33m')
green=$(printf '\033[0;32m')
reset=$(printf '\033[0;00m')
blue=$(printf '\033[0;34m')
red=$(printf '\033[0;31m')
yellow=$(printf '\033[0;93m')
purple=$(printf '\033[0;95m')
cyan=$(printf '\033[1;36m')

bold=$(printf '\033[1m')
underline=$(printf '\033[4m')
reversed=$(printf '\033[7m')

if [[ $# -eq 0 ]] ; then
	cat <<-EOF
		Usage: $0 <configuration_directory> [<tags>]

		Tags are optional and allow you to deploy only certain components
		Run ./tools/list-tags.py to see all available tags

		WARNING: Tags assume that the "backend-common" or "relay-common" and "users"
		roles are already deployed to the server, if this is not the case
		add "backend-common" or "relay-common" and "users" as a tag
	EOF
	exit 1
fi

CONFIG_PATH="${PWD}/$1"
HOST_FILE="${CONFIG_PATH}/hosts.yml"
CONFIG_FILE="${CONFIG_PATH}/configuration.yml"
EXPORT_PATH="${CONFIG_PATH}/Exports_Autogenerated/"
VAULT_FILE="${CONFIG_PATH}/vaulted_vars.yml"

echo
echo "__________           .___  __      __.__                         .___"
echo "\______   \ ____   __| _/ /  \    /  \__|____________ _______  __| _/"
echo " |       _// __ \ / __ |  \   \/\/   /  \___   /\__  \\_  __ \/ __ |"
echo " |    |   \  ___// /_/ |   \        /|  |/    /  / __ \|  | \/ /_/ |"
echo " |____|_  /\___  >____ |    \__/\  / |__/_____ \(____  /__|  \____ |"
echo "        \/     \/     \/         \/           \/     \/           \/"
echo
echo "                  --- Deploying Infrastructure ---                  "
echo
echo

cat <<-EOF
	Have you checked all requirements? If they are not met, this will fail.
	Check the requirements with ${green}python3 tools/check-prerequisites.py ${CONFIG_PATH}${reset}
EOF
read -p "Do you want to continue? [y/N] " -n 1 -r
echo

if [[ ! ${REPLY} =~ ^[Yy]$ ]]; then
	exit 1
fi

if [ ! -f "${HOST_FILE}" ]; then
	echo "Hosts file (hosts) does not exist in ${CONFIG_PATH}."
	exit 1
fi

if [ ! -f "${CONFIG_FILE}" ]; then
	echo "Config file (configuration.yml) file does not exist in ${CONFIG_PATH}."
	exit 1
fi

mkdir -p ${EXPORT_PATH}

if [[ $# -eq 1 ]] ; then
	ansible-playbook -i "${HOST_FILE}" -e "@${CONFIG_FILE}" -e "@${VAULT_FILE}" --ask-vault-pass --extra-vars "export_path=${EXPORT_PATH} config_path=${CONFIG_PATH}" playbook.yml
fi

if [[ $# -eq 2 ]] ; then
	TAGS="$2"
	cat <<-EOF

		WARNING: Tags assume that the "backend-common" or "relay-common" and "users"
		roles are already deployed to the server, if this is not the case
		add "backend-common" or "relay-common"  and "users" as a tag or your deployment
		will fail

	EOF
	ansible-playbook -i "${HOST_FILE}" -e "@${CONFIG_FILE}" -e "@${VAULT_FILE}" --tags "${TAGS}" --ask-vault-pass --extra-vars "export_path=${EXPORT_PATH} config_path=${CONFIG_PATH}" playbook.yml
fi
cat <<-EOF
	------------------------------------- DONE -------------------------------------
	- Consider running ${green}./tools/create-ssh-config.py ${CONFIG_PATH}${reset} to create your SSH Config
	- Consider running ${green}./tools/diagram.py ${CONFIG_PATH}${reset} to create a diagram of your infra
	- Configure your DNS settings for phishing and CobaltStrike campaigns. Consider running ${green}cat ${CONFIG_PATH}/Exports_Autogenerated/dns_configs/*${reset}
EOF
