---

# /////////////////////////////////////////////////////////////////////////////
#                         RT INFRASTRUCTURE CONFIGURATION
#
# FILE STRUCTURE:
# - BASIC CONFIGURATION   - List all relevant servers and IP addresses
# - ROLES (Relays)        - Configuration for all Relays
# - ROLES (Backends)      - Configuration for all Backends
# /////////////////////////////////////////////////////////////////////////////

# /////////////////////////////////////////////////////////////////////////////
#                              BASIC CONFIGURATION
#
# Please configure all Backend and relay hosts in the following categories
# All hosts should have a name and IP address set
# /////////////////////////////////////////////////////////////////////////////

\VAR{backends}

\VAR{relays}

# /////////////////////////////////////////////////////////////////////////////
#                                   ROLES
#
# The categories are defining the variables for all the roles that will be
# installed. So the top level variable will be used to kick off a role during
# deployment
# /////////////////////////////////////////////////////////////////////////////

# ############################# PHISHING RELAYS ###############################
# Define the list of phishing relays
# hosts: Use identical names as the hosts defined at the top level "relays"
# vars:
# - "domain_name": The domain name pointing to this server
# - "ansible_host": IP Address of the relay
# - "client_profiles": These will be the names for the ovpn-profiles that will
#   be used to connect to this relay.

# #############################################################################

\VAR{relays_phishing}

# ############################## OSINT RELAYS #################################
# Define the list of OSINT relays
# hosts: Use identical names as the hosts defined at the top level "relays"
# vars:
# - "ansible_host": IP Address of the relay
# - "client_profiles": These will be the names for the ovpn-profiles that will
#   be used to connect to this relay.

# #############################################################################

\VAR{relays_osint}

# ########################## REVERSE NGINX RELAYS #############################
# Define the list of Reverse NGINX relays
# hosts: Use UNIQUE names as the hosts defined at the top level "relays"
#        This is so you will be able to install multiple reverse nginx-relays
#        on the same host that redirect to other backends
# vars:
# - "ansible_host": IP Address of the relay
# - "backend_port": The port that is open on the backend docker, default: 80
# - "domain_name": The domain name pointing to this server
# - "nginx_bounce_site": Visitors without Secret String will be redirected here
# - "relay_to_client_profile": indicate to what client profile requests will be relayed
# - "secret_strings": Everything to <host>/secret_string will be relayed
# - "forward_path": The url on the backend that requests will be relayed to
# - "connection_method": Indicate whether the backend runs HTTP or HTTPS
# - "client_profiles": These will be the names for the ovpn-profiles that will
#   be used to connect to this relay
# Note: This can be installed in addition to a phishing relay

# #############################################################################

\VAR{relays_nginx}

# ############################## DROPBOX RELAYS #################################
# Define the list of Dropbox relays
# hosts: Use identical names as the hosts defined at the top level "relays"
# vars:
# - "ansible_host": IP Address of the relay
# - "dropbox_docker_ip": Static IP of dropbox docker, must be in range of internal_vpn_ip_space
# - "exposed_port": What port on the relay will be forwarded to the backend dropbox docker
# - "client_profiles": These will be the names for the ovpn-profiles that will
#   be used to connect to this relay.

\VAR{relays_dropbox}

############################# COBALTSTRIKE RELAYS ##############################
# Define the list of CobaltStrike DNS relays
# hosts: Use identical names as the hosts defined at the top level "relays"
# vars:
# - "domain_name": The domain name pointing to this server
# - "ansible_host": IP Address of the relay
# - "dns_beacon_subdomain": Subdomain for CS DNS Traffic
# - "relay_to_client_profile": indicate to what client profile requests will be relayed

\VAR{relays_cobalt_strike}

# ######################### BACKENDS COBALT STRIKE ############################
# Define the list of Cobalt Strike backends
# hosts: Please use UNIQUE names, as they indicate different CS campaings
#        handled by the same C2 system
# vars:
# - "ansible_host": IP Address of the C2 server
# - "dns_beacon_subdomain": Subdomain for CS DNS Traffic
# - "domain_name": The domain name pointing to the associated relay server
# - "http_get_uri": Variable for the malleable profile, must match string @ relay
# - "http_post_uri": Variable for the malleable profile, must match string @ relay
# - "http_stager_64_uri": Variable for the malleable profile, must match string @ relay
# - "http_stager_86_uri": Variable for the malleable profile, must match string @ relay
# - "identification": Name of this CS campaign
# - "malleable_profile": Chosen malleable profile
# - "relay_host": The host used as relay, use the name as defined in this file
# - "relay_host_ip": IP Address of the Relay server

# #############################################################################

\VAR{backends_cobalt_strike}

# ######################### BACKENDS WEB CATCHERS #############################
# Define the list of Web Catcher backends
# hosts: Please use UNIQUE names, as they indicate campaigns on the same C2
# vars:
# - "ansible_host":  IP Address of the C2 server
# - "relay_host":    The host used as relay, use the name as defined in this file
# - "relay_host_ip": IP Address of the Relay server
# Note: This can be deployed multiple times to the same C2 for more campaigns
#       Just make sure to use unique relays

# #############################################################################

\VAR{backends_web_catcher}

# ################################# OSINT #####################################
# hosts: Please use the same name as indicated in the basic configuration
# vars:
# - "ansible_host": IP Address of the C2 server
# - "relay_host":    The host used as relay, use the name as defined in this file
# - "relay_host_ip": IP Address of the Relay server

# #############################################################################

\VAR{backends_osint}

# ########################### BACKENDS PHISHING ###############################
# Define the list of Phishing backends
# hosts: Please use UNIQUE names, as they indicate different Phishing campaings
#        handled by the same C2 system
# vars:
# - "ansible_host": IP Address of the C2 server
# - "domain_name": The domain name pointing to the associated relay server
# - "gophish_admin_port": The exposed port for gophish management (MUST BE UNIQUE!)
# - "relay_host":    The host used as relay, use the name as defined in this file
# - "relay_host_ip": IP Address of the Relay server
# - "send_from":     Preconfigured names for sending profiles
# Note2: This can be deployed multiple times to the same C2 for more campaigns
#        Just make sure to use unique relays and unique admin ports

\VAR{backends_gophish}

\VAR{backends_manual_phish}

# ######################### BACKENDS DROPBOXES #############################
# Define the list of Dropbox backends
# hosts: Please use UNIQUE names, as they indicate campaigns on the same C2
# vars:
# - "ansible_host":  IP Address of the C2 server
# - "relay_host":    The host used as relay, use the name as defined in this file
# - "relay_host_ip": IP Address of the Relay server
# - "exposed_port":  What port on the relay will be forwarded to this backend dropbox docker

\VAR{backends_dropbox}
