---
- name: "***** BACKEND: Preparing the operating system *****"
  include_tasks: os-prep.yml

- name: "***** BACKEND: Harden the server *****"
  include_tasks: backend-hardening.yml

- name: "***** BACKEND: Set up toolkit *****"
  include_tasks: toolkit.yml

- name: "***** BACKEND: Set up complete audit logging *****"
  include_tasks: full-system-logging.yml

- name: "***** BACKEND: Set up the help files *****"
  include_tasks: help-prep.yml
