---
# vars file for relay-phishing

postfix_config:
  myhostname: "{{ domain_name }}"
  milter_protocol: 2
  milter_default_action: accept
  smtpd_milters: inet:localhost:12345
  non_smtpd_milters: inet:localhost:12345
  mydestination: '"{{ domain_name }}, DEVELOPMENT-phishing-relay, localhost.localdomain, localhost"'
  mynetworks: '"127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128 10.8.0.0/24"'
  smtpd_tls_cert_file: "/etc/letsencrypt/live/{{ domain_name }}/fullchain.pem"
  smtpd_tls_key_file: "/etc/letsencrypt/live/{{ domain_name }}/privkey.pem"
  smtpd_tls_security_level: may
  smtp_tls_security_level: encrypt
  smtpd_use_tls: "no"
  virtual_alias_domains: '"{{ domain_name }}"'
  virtual_alias_maps: "hash:/etc/postfix/virtual"

client_profiles:
  - "gophish"       # The gophish profile can be used to let an nginx reverse proxy automatically choose this connection
  - "manual-phish"

help_marker: "relay_phishing_{{ domain_name }}"
